### ISSUE TITLE
转载申请

### ISSUE THREAD

**Issue by sisterAn** [Michael-lzg/my--article#1]
你好，webpack的异步加载及分包策略可以转载到公众号前端瓶子君上吗？会标明作者与来源，感谢

**Comment by Michael-lzg** [comment]
可以的，欢迎star哦

**Comment by Michael-lzg** [comment]
> 你好，webpack的异步加载及分包策略可以转载到公众号前端瓶子君上吗？会标明作者与来源，感谢

可以的，欢迎star哦

**Comment by sisterAn** [comment]
已star，谢谢
